export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const SAVE_PROJECTS = 'SAVE_PROJECTS'

export const FETCH_PROJECT_DETAILS = 'FETCH_PROJECT_DETAILS';
export const SAVE_PROJECT_DETAILS = 'SAVE_PROJECT_DETAILS';

export const FETCH_BIDS = 'FETCH_BIDS';
export const SAVE_BIDS = 'SAVE_BIDS';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const POST_NEW_PROJECT = 'POST_NEW_PROJECT';
export const POST_NEW_PROJECT_SUCCESS = 'POST_NEW_PROJECT_SUCCESS';
export const CLEAR_POST_NEW_PROJECT_SUCCESS = 'CLEAR_POST_NEW_PROJECT_SUCCESS';

export const POST_NEW_BID = 'POST_NEW_BID';
export const POST_NEW_BID_SUCCESS = 'POST_NEW_BID_SUCCESS';
export const CLEAR_POST_NEW_BID_SUCCESS = 'CLEAR_POST_NEW_BID_SUCCESS';